version: 2.1

jobs:
  build-and-test-job:
    docker:
      - image: timlepangea/circleci-dotnet:6.0
    steps:
      - checkout
      - run:
          working_directory: SampleApp.Tests
          name: Run tests
          command: |
            dotnet test

workflows:
  MySampleWorkFlow:
    jobs:
      - build-and-test-job
